import "../app/globals.css";
import { Inter as FontSans } from "next/font/google";
import type { Metadata } from "next";
import { getFeeds } from "@/app/actions";
import AddFeed from "@/components/AddFeed";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Briefing Officer",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const feeds = await getFeeds();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
          Briefing Officer
        </h1>
        <div className=""></div>
        <div>
          <ul>
            {feeds.map((feed) => (
              <li key={feed.id}>
                <a href={`/feed/${feed.id}`}>{feed.title}</a>
              </li>
            ))}
          </ul>
          <AddFeed />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
