import { getFeeds } from "@/app/actions";
import AddFeed from "@/components/AddFeed";
import FeedNavigation from "@/components/layout/FeedNavigation";
import { Separator } from "@/components/ui/separator";
import Typography from "@/components/ui/typography";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Link from "next/link";
import "../app/globals.css";

export const metadata: Metadata = {
  title: "Briefing Officer",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const feeds = await getFeeds();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <div className="w-full bg-black p-4 text-white">
          <Typography variant="h1">
            <Link href="/">Briefing Officer</Link>
          </Typography>
        </div>
        <div className="m-2 mt-4 flex flex-row gap-4">
          <div className="flex flex-col gap-4">
            <FeedNavigation feeds={feeds} />

            <Separator />

            <div className="px-2">
              <AddFeed />
            </div>
          </div>

          <Separator className="h-auto py-4" orientation="vertical" />

          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
