{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "briefing-officer.fullname" . }}
  labels:
    {{- include "briefing-officer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.httpRoute.annotations | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "briefing-officer.fullname" . }}
          port: {{ .Values.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/health
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
            statusCode: 302
{{- end }}
