{{- if not .Values.azureOpenAi.existingApiKeySecretName}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "briefing-officer.fullname" . }}
  labels:
    {{- include "briefing-officer.labels" . | nindent 4 }}
data:
  AZURE_OPENAI_API_KEY: {{ .Values.azureOpenAi.apiKey | b64enc | quote }}
{{- end }}