name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: runner-set-marcusleg-briefing-officer

    env:
      DATABASE_URL: /tmp/database.db

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Use Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '22.x'
      - name: Install Dependencies
        run: npm ci
      - name: Generate Prisma Client and create database file
        run: npx prisma generate && npx prisma db push
      - name: Run Build
        run: npm run build