name: Build
on: push

jobs:
  build:
    runs-on: runner-set-marcusleg-briefing-officer

    env:
      DATABASE_URL: file:/tmp/database.sqlite
      OPENAI_API_KEY=: any-value-will-do-at-build-time
      OPENAI_API_URL=: http://localhost

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Use Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Generate Prisma Client and create database file
        run: npx prisma generate && npx prisma db push
      - name: Run Build
        run: npm run build
