name: Format
on: push

jobs:
  build:
    runs-on: runner-set-marcusleg-briefing-officer

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Check Code Formatting
        run: npm run format:check
