name: Lint
on: push

jobs:
  lint:
    runs-on: runner-set-marcusleg-briefing-officer

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
